### ISSUE TITLE
Dashboard not loading

### ISSUE THREAD

**Issue by blizzardengle** [invoiceninja/flutter-mobile#30]
I have the latest version of the Android app and Self Host of Invoice Ninja. I thought the Dashboard feature was not implemented yet until I saw a screenshot in this issue: https://github.com/invoiceninja/flutter-mobile/issues/20#issue-339615970

My Dashboard never loads and just shows the loading icon forever:

![screenshot](https://user-images.githubusercontent.com/11205240/44735673-5579ad80-aaaa-11e8-9197-9619fddfa453.jpg)

I am using Android 7 on a Moto X Pure edition.

**Comment by hillelcoren** [comment]
I'm not seeing this problem, we'll try add more more debugging in the next version to track down the issue.

**Comment by hillelcoren** [comment]
When you get a chance please try again with the latest versions of the web/mobile apps. 

We fixed a related error which I'm hoping will also resolve this issue.

**Comment by blizzardengle** [comment]
It was still broken so I went to force update the app in the Play Store and noticed you marked the app as DELETE so I deleted it and found the newest version and now I can't login. I get the error: **The minimum version is v4.5.4**

I just [looked ](https://invoice-ninja.readthedocs.io/en/latest/update.html)and only see 4.3 as the latest release of Invoice Ninja.

**Comment by hillelcoren** [comment]
I see... those are the update notes for breaking changes, most updates have no notes.

You can see our full release list here:

https://github.com/invoiceninja/invoiceninja/releases

**Comment by blizzardengle** [comment]
Ok I got everything updated and working correctly but this bug is still present. Could the server be the issue? I noticed after I updated the site and logged into the app for the first time my server froze for a bit as it pulled all the info into the app.

**Comment by hillelcoren** [comment]
It could be specific data in the account, if you want to test it you could add a blank company in the web app. 

We'll keep looking into it...

**Comment by hillelcoren** [comment]
Thanks for the info!

We won't be able to easily detect a deleted company but the app shouldn't hang when reloading the data.

**Comment by hillelcoren** [comment]
We've fixed a bug which prevented the app from showing the error details when the dashboard failed to load, hopefully this will help track down the source of the problem.

**Comment by hillelcoren** [comment]
Can you try updating app/Ninja/Transformers/ActivityTransformer.php with this version of the file:

https://raw.githubusercontent.com/invoiceninja/invoiceninja/develop/app/Ninja/Transformers/ActivityTransformer.php

**Comment by blizzardengle** [comment]
Yep, that worked!

**Comment by hillelcoren** [comment]
Great to hear, thanks for letting us know!
